export const defaultCategories = [
  // Income categories
  {
    name: 'Salary',
    color: '#4CAF50',
    icon: 'briefcase',
    isSystem: true,
    isIncome: true,
    isExpense: false,
    isInvestment: false,
  },
  {
    name: 'Bonus',
    color: '#8BC34A',
    icon: 'award',
    isSystem: true,
    isIncome: true,
    isExpense: false,
    isInvestment: false,
  },

  {
    name: 'Interest',
    color: '#3F51B5',
    icon: 'trending-up',
    isSystem: true,
    isIncome: true,
    isExpense: false,
    isInvestment: false,
  },

  // Expense categories
  {
    name: 'Food & Dining',
    color: '#FF5722',
    icon: 'utensils',
    isSystem: true,
    isIncome: false,
    isExpense: true,
    isInvestment: false,
  },
  {
    name: 'Groceries',
    color: '#FF9800',
    icon: 'shopping-cart',
    isSystem: true,
    isIncome: false,
    isExpense: true,
    isInvestment: false,
  },
  {
    name: 'Housing Rent',
    color: '#E91E63',
    icon: 'home',
    isSystem: true,
    isIncome: false,
    isExpense: true,
    isInvestment: false,
  },
  {
    name: 'Utilities',
    color: '#9C27B0',
    icon: 'zap',
    isSystem: true,
    isIncome: false,
    isExpense: true,
    isInvestment: false,
  },
  {
    name: 'Internet & Phone',
    color: '#2196F3',
    icon: 'wifi',
    isSystem: true,
    isIncome: false,
    isExpense: true,
    isInvestment: false,
  },
  {
    name: 'Entertainment',
    color: '#673AB7',
    icon: 'film',
    isSystem: true,
    isIncome: false,
    isExpense: true,
    isInvestment: false,
  },
  {
    name: 'Shopping',
    color: '#F44336',
    icon: 'shopping-bag',
    isSystem: true,
    isIncome: false,
    isExpense: true,
    isInvestment: false,
  },

  {
    name: 'Health & Medical',
    color: '#03A9F4',
    icon: 'activity',
    isSystem: true,
    isIncome: false,
    isExpense: true,
    isInvestment: false,
  },

  {
    name: 'Travel',
    color: '#009688',
    icon: 'map',
    isSystem: true,
    isIncome: false,
    isExpense: true,
    isInvestment: false,
  },
  {
    name: 'Insurance',
    color: '#455A64',
    icon: 'shield',
    isSystem: true,
    isIncome: false,
    isExpense: true,
    isInvestment: false,
  },
  {
    name: 'Taxes',
    color: '#795548',
    icon: 'file-text',
    isSystem: true,
    isIncome: false,
    isExpense: true,
    isInvestment: false,
  },
  {
    name: 'Miscellaneous',
    color: '#9E9E9E',
    icon: 'more-horizontal',
    isSystem: true,
    isIncome: false,
    isExpense: true,
    isInvestment: false,
  },

  // Investment categories
  {
    name: 'Stocks',
    color: '#3F51B5',
    icon: 'bar-chart-2',
    isSystem: true,
    isIncome: false,
    isExpense: false,
    isInvestment: true,
  },
  {
    name: 'Mutual Funds',
    color: '#2196F3',
    icon: 'pie-chart',
    isSystem: true,
    isIncome: false,
    isExpense: false,
    isInvestment: true,
  },
  {
    name: 'Gold',
    color: '#FFC107',
    icon: 'circle',
    isSystem: true,
    isIncome: false,
    isExpense: false,
    isInvestment: true,
  },
];
